service: example-offline-http

plugins:
  - serverless-offline

custom:
  defaults:
    stage: dev

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment: ${file(./config/env.yml):${opt:stage, self:custom.defaults.stage}}

functions:
  events:
    handler: functions/eventsHttp.handler
    events:
      - http:
          method: POST
          path: events
          cors: true
  eventsStream:
    handler: functions/eventsStream.handler
    events:
      - stream:
          type: kinesis
          #arn: need an arn
          batchSize: 100
          startingPosition: LATEST

#resources: need Resources entry for kinesis  